[package]
name = "physynth"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.17.0"
egui-macroquad = "0.9.0"
macroquad = "0.3.6"
midir = "0.7.0"
rodio = "0.15.0"
